---

- name: include os-specific settings
  include_vars: "{{ ansible_os_family | lower }}.yml"
  tags: always

- import_tasks: prepare.yml
  tags: [install, prepare]

- import_tasks: install.yml
  tags: install

- import_tasks: configure.yml
  tags: configure
